// Curated list of ~230 major airports for client-side autocomplete.
// [IATA code, airport name, city, country]. Not exhaustive — a free-text
// 3-letter code still works for anything missing.
export type Airport = [string, string, string, string];

export const AIRPORTS: Airport[] = [
  // North America — US
  ["ATL", "Hartsfield-Jackson Atlanta International", "Atlanta", "United States"],
  ["LAX", "Los Angeles International", "Los Angeles", "United States"],
  ["ORD", "O'Hare International", "Chicago", "United States"],
  ["MDW", "Chicago Midway", "Chicago", "United States"],
  ["DFW", "Dallas/Fort Worth International", "Dallas", "United States"],
  ["DAL", "Dallas Love Field", "Dallas", "United States"],
  ["DEN", "Denver International", "Denver", "United States"],
  ["JFK", "John F. Kennedy International", "New York", "United States"],
  ["LGA", "LaGuardia", "New York", "United States"],
  ["EWR", "Newark Liberty International", "Newark / New York", "United States"],
  ["SFO", "San Francisco International", "San Francisco", "United States"],
  ["OAK", "Oakland International", "Oakland", "United States"],
  ["SJC", "San Jose Mineta International", "San Jose", "United States"],
  ["SEA", "Seattle-Tacoma International", "Seattle", "United States"],
  ["LAS", "Harry Reid International", "Las Vegas", "United States"],
  ["MCO", "Orlando International", "Orlando", "United States"],
  ["MIA", "Miami International", "Miami", "United States"],
  ["FLL", "Fort Lauderdale-Hollywood", "Fort Lauderdale", "United States"],
  ["PBI", "Palm Beach International", "West Palm Beach", "United States"],
  ["TPA", "Tampa International", "Tampa", "United States"],
  ["RSW", "Southwest Florida International", "Fort Myers", "United States"],
  ["JAX", "Jacksonville International", "Jacksonville", "United States"],
  ["PHX", "Phoenix Sky Harbor", "Phoenix", "United States"],
  ["IAH", "George Bush Intercontinental", "Houston", "United States"],
  ["HOU", "William P. Hobby", "Houston", "United States"],
  ["BOS", "Logan International", "Boston", "United States"],
  ["MSP", "Minneapolis-Saint Paul International", "Minneapolis", "United States"],
  ["DTW", "Detroit Metropolitan", "Detroit", "United States"],
  ["PHL", "Philadelphia International", "Philadelphia", "United States"],
  ["CLT", "Charlotte Douglas International", "Charlotte", "United States"],
  ["BWI", "Baltimore/Washington International", "Baltimore", "United States"],
  ["IAD", "Washington Dulles International", "Washington, D.C.", "United States"],
  ["DCA", "Ronald Reagan Washington National", "Washington, D.C.", "United States"],
  ["SLC", "Salt Lake City International", "Salt Lake City", "United States"],
  ["SAN", "San Diego International", "San Diego", "United States"],
  ["AUS", "Austin-Bergstrom International", "Austin", "United States"],
  ["SAT", "San Antonio International", "San Antonio", "United States"],
  ["STL", "St. Louis Lambert International", "St. Louis", "United States"],
  ["HNL", "Daniel K. Inouye International", "Honolulu", "United States"],
  ["OGG", "Kahului", "Maui", "United States"],
  ["PDX", "Portland International", "Portland", "United States"],
  ["MSY", "Louis Armstrong New Orleans International", "New Orleans", "United States"],
  ["RDU", "Raleigh-Durham International", "Raleigh", "United States"],
  ["SMF", "Sacramento International", "Sacramento", "United States"],
  ["BNA", "Nashville International", "Nashville", "United States"],
  ["CLE", "Cleveland Hopkins International", "Cleveland", "United States"],
  ["CVG", "Cincinnati/Northern Kentucky International", "Cincinnati", "United States"],
  ["PIT", "Pittsburgh International", "Pittsburgh", "United States"],
  ["IND", "Indianapolis International", "Indianapolis", "United States"],
  ["MCI", "Kansas City International", "Kansas City", "United States"],
  ["CMH", "John Glenn Columbus International", "Columbus", "United States"],
  ["ANC", "Ted Stevens Anchorage International", "Anchorage", "United States"],
  // Canada
  ["YYZ", "Toronto Pearson International", "Toronto", "Canada"],
  ["YVR", "Vancouver International", "Vancouver", "Canada"],
  ["YUL", "Montréal-Trudeau International", "Montreal", "Canada"],
  ["YYC", "Calgary International", "Calgary", "Canada"],
  ["YEG", "Edmonton International", "Edmonton", "Canada"],
  ["YOW", "Ottawa Macdonald-Cartier", "Ottawa", "Canada"],
  ["YHZ", "Halifax Stanfield", "Halifax", "Canada"],
  // Mexico, Central America, Caribbean
  ["MEX", "Benito Juárez International", "Mexico City", "Mexico"],
  ["CUN", "Cancún International", "Cancun", "Mexico"],
  ["GDL", "Guadalajara International", "Guadalajara", "Mexico"],
  ["MTY", "Monterrey International", "Monterrey", "Mexico"],
  ["SJD", "Los Cabos International", "San José del Cabo", "Mexico"],
  ["PVR", "Puerto Vallarta International", "Puerto Vallarta", "Mexico"],
  ["SJU", "Luis Muñoz Marín International", "San Juan", "Puerto Rico"],
  ["PTY", "Tocumen International", "Panama City", "Panama"],
  ["SJO", "Juan Santamaría International", "San José", "Costa Rica"],
  ["LIR", "Guanacaste Airport", "Liberia", "Costa Rica"],
  ["GUA", "La Aurora International", "Guatemala City", "Guatemala"],
  ["SAL", "El Salvador International", "San Salvador", "El Salvador"],
  ["HAV", "José Martí International", "Havana", "Cuba"],
  ["MBJ", "Sangster International", "Montego Bay", "Jamaica"],
  ["NAS", "Lynden Pindling International", "Nassau", "Bahamas"],
  ["PUJ", "Punta Cana International", "Punta Cana", "Dominican Republic"],
  ["SDQ", "Las Américas International", "Santo Domingo", "Dominican Republic"],
  ["AUA", "Queen Beatrix International", "Oranjestad", "Aruba"],
  ["CUR", "Curaçao International", "Willemstad", "Curaçao"],
  // South America
  ["GRU", "São Paulo/Guarulhos International", "Sao Paulo", "Brazil"],
  ["GIG", "Rio de Janeiro/Galeão International", "Rio de Janeiro", "Brazil"],
  ["BSB", "Brasília International", "Brasilia", "Brazil"],
  ["EZE", "Ministro Pistarini (Ezeiza)", "Buenos Aires", "Argentina"],
  ["AEP", "Aeroparque Jorge Newbery", "Buenos Aires", "Argentina"],
  ["SCL", "Arturo Merino Benítez International", "Santiago", "Chile"],
  ["LIM", "Jorge Chávez International", "Lima", "Peru"],
  ["CUZ", "Alejandro Velasco Astete International", "Cusco", "Peru"],
  ["BOG", "El Dorado International", "Bogota", "Colombia"],
  ["MDE", "José María Córdova International", "Medellin", "Colombia"],
  ["CTG", "Rafael Núñez International", "Cartagena", "Colombia"],
  ["UIO", "Mariscal Sucre International", "Quito", "Ecuador"],
  ["GYE", "José Joaquín de Olmedo International", "Guayaquil", "Ecuador"],
  ["MVD", "Carrasco International", "Montevideo", "Uruguay"],
  ["ASU", "Silvio Pettirossi International", "Asuncion", "Paraguay"],
  ["LPB", "El Alto International", "La Paz", "Bolivia"],
  // Europe
  ["LHR", "Heathrow", "London", "United Kingdom"],
  ["LGW", "Gatwick", "London", "United Kingdom"],
  ["STN", "Stansted", "London", "United Kingdom"],
  ["LTN", "Luton", "London", "United Kingdom"],
  ["LCY", "London City", "London", "United Kingdom"],
  ["MAN", "Manchester", "Manchester", "United Kingdom"],
  ["EDI", "Edinburgh", "Edinburgh", "United Kingdom"],
  ["GLA", "Glasgow", "Glasgow", "United Kingdom"],
  ["BHX", "Birmingham", "Birmingham", "United Kingdom"],
  ["DUB", "Dublin", "Dublin", "Ireland"],
  ["SNN", "Shannon", "Shannon", "Ireland"],
  ["CDG", "Charles de Gaulle", "Paris", "France"],
  ["ORY", "Orly", "Paris", "France"],
  ["NCE", "Nice Côte d'Azur", "Nice", "France"],
  ["LYS", "Lyon-Saint Exupéry", "Lyon", "France"],
  ["MRS", "Marseille Provence", "Marseille", "France"],
  ["TLS", "Toulouse-Blagnac", "Toulouse", "France"],
  ["FRA", "Frankfurt", "Frankfurt", "Germany"],
  ["MUC", "Munich", "Munich", "Germany"],
  ["BER", "Berlin Brandenburg", "Berlin", "Germany"],
  ["DUS", "Düsseldorf", "Dusseldorf", "Germany"],
  ["HAM", "Hamburg", "Hamburg", "Germany"],
  ["CGN", "Cologne Bonn", "Cologne", "Germany"],
  ["STR", "Stuttgart", "Stuttgart", "Germany"],
  ["AMS", "Schiphol", "Amsterdam", "Netherlands"],
  ["EIN", "Eindhoven", "Eindhoven", "Netherlands"],
  ["BRU", "Brussels", "Brussels", "Belgium"],
  ["CRL", "Brussels South Charleroi", "Charleroi", "Belgium"],
  ["LUX", "Luxembourg", "Luxembourg", "Luxembourg"],
  ["ZRH", "Zurich", "Zurich", "Switzerland"],
  ["GVA", "Geneva", "Geneva", "Switzerland"],
  ["BSL", "EuroAirport Basel", "Basel", "Switzerland"],
  ["VIE", "Vienna International", "Vienna", "Austria"],
  ["MAD", "Adolfo Suárez Madrid-Barajas", "Madrid", "Spain"],
  ["BCN", "Barcelona-El Prat", "Barcelona", "Spain"],
  ["AGP", "Málaga-Costa del Sol", "Malaga", "Spain"],
  ["PMI", "Palma de Mallorca", "Palma", "Spain"],
  ["VLC", "Valencia", "Valencia", "Spain"],
  ["SVQ", "Seville", "Seville", "Spain"],
  ["ALC", "Alicante-Elche", "Alicante", "Spain"],
  ["IBZ", "Ibiza", "Ibiza", "Spain"],
  ["LIS", "Humberto Delgado", "Lisbon", "Portugal"],
  ["OPO", "Francisco Sá Carneiro", "Porto", "Portugal"],
  ["FAO", "Faro", "Faro", "Portugal"],
  ["FNC", "Cristiano Ronaldo Madeira", "Funchal", "Portugal"],
  ["FCO", "Rome Fiumicino", "Rome", "Italy"],
  ["CIA", "Rome Ciampino", "Rome", "Italy"],
  ["MXP", "Milan Malpensa", "Milan", "Italy"],
  ["LIN", "Milan Linate", "Milan", "Italy"],
  ["BGY", "Milan Bergamo", "Bergamo", "Italy"],
  ["VCE", "Venice Marco Polo", "Venice", "Italy"],
  ["NAP", "Naples International", "Naples", "Italy"],
  ["FLR", "Florence", "Florence", "Italy"],
  ["BLQ", "Bologna", "Bologna", "Italy"],
  ["CTA", "Catania-Fontanarossa", "Catania", "Italy"],
  ["PMO", "Palermo", "Palermo", "Italy"],
  ["ATH", "Athens International", "Athens", "Greece"],
  ["SKG", "Thessaloniki", "Thessaloniki", "Greece"],
  ["HER", "Heraklion", "Heraklion / Crete", "Greece"],
  ["JTR", "Santorini", "Santorini", "Greece"],
  ["JMK", "Mykonos", "Mykonos", "Greece"],
  ["CPH", "Copenhagen", "Copenhagen", "Denmark"],
  ["OSL", "Oslo Gardermoen", "Oslo", "Norway"],
  ["ARN", "Stockholm Arlanda", "Stockholm", "Sweden"],
  ["GOT", "Gothenburg Landvetter", "Gothenburg", "Sweden"],
  ["HEL", "Helsinki-Vantaa", "Helsinki", "Finland"],
  ["KEF", "Keflavík International", "Reykjavik", "Iceland"],
  ["WAW", "Warsaw Chopin", "Warsaw", "Poland"],
  ["KRK", "Kraków John Paul II", "Krakow", "Poland"],
  ["GDN", "Gdańsk Lech Wałęsa", "Gdansk", "Poland"],
  ["PRG", "Václav Havel Prague", "Prague", "Czech Republic"],
  ["BUD", "Budapest Ferenc Liszt", "Budapest", "Hungary"],
  ["OTP", "Henri Coandă International", "Bucharest", "Romania"],
  ["SOF", "Sofia", "Sofia", "Bulgaria"],
  ["BEG", "Belgrade Nikola Tesla", "Belgrade", "Serbia"],
  ["ZAG", "Zagreb", "Zagreb", "Croatia"],
  ["SPU", "Split", "Split", "Croatia"],
  ["DBV", "Dubrovnik", "Dubrovnik", "Croatia"],
  ["LJU", "Ljubljana Jože Pučnik", "Ljubljana", "Slovenia"],
  ["TIA", "Tirana International", "Tirana", "Albania"],
  ["RIX", "Riga International", "Riga", "Latvia"],
  ["TLL", "Tallinn", "Tallinn", "Estonia"],
  ["VNO", "Vilnius", "Vilnius", "Lithuania"],
  ["IST", "Istanbul Airport", "Istanbul", "Turkey"],
  ["SAW", "Istanbul Sabiha Gökçen", "Istanbul", "Turkey"],
  ["AYT", "Antalya", "Antalya", "Turkey"],
  ["ADB", "Izmir Adnan Menderes", "Izmir", "Turkey"],
  ["ESB", "Ankara Esenboğa", "Ankara", "Turkey"],
  ["MLA", "Malta International", "Valletta", "Malta"],
  ["LCA", "Larnaca International", "Larnaca", "Cyprus"],
  ["PFO", "Paphos International", "Paphos", "Cyprus"],
  // Middle East
  ["DXB", "Dubai International", "Dubai", "United Arab Emirates"],
  ["AUH", "Zayed International", "Abu Dhabi", "United Arab Emirates"],
  ["DOH", "Hamad International", "Doha", "Qatar"],
  ["RUH", "King Khalid International", "Riyadh", "Saudi Arabia"],
  ["JED", "King Abdulaziz International", "Jeddah", "Saudi Arabia"],
  ["KWI", "Kuwait International", "Kuwait City", "Kuwait"],
  ["BAH", "Bahrain International", "Manama", "Bahrain"],
  ["MCT", "Muscat International", "Muscat", "Oman"],
  ["AMM", "Queen Alia International", "Amman", "Jordan"],
  ["BEY", "Beirut-Rafic Hariri International", "Beirut", "Lebanon"],
  ["TLV", "Ben Gurion", "Tel Aviv", "Israel"],
  // Africa
  ["CAI", "Cairo International", "Cairo", "Egypt"],
  ["HRG", "Hurghada International", "Hurghada", "Egypt"],
  ["SSH", "Sharm El Sheikh International", "Sharm El Sheikh", "Egypt"],
  ["CMN", "Mohammed V International", "Casablanca", "Morocco"],
  ["RAK", "Marrakesh Menara", "Marrakesh", "Morocco"],
  ["TUN", "Tunis-Carthage International", "Tunis", "Tunisia"],
  ["ALG", "Houari Boumediene", "Algiers", "Algeria"],
  ["LOS", "Murtala Muhammed International", "Lagos", "Nigeria"],
  ["ABV", "Nnamdi Azikiwe International", "Abuja", "Nigeria"],
  ["ACC", "Kotoka International", "Accra", "Ghana"],
  ["DSS", "Blaise Diagne International", "Dakar", "Senegal"],
  ["ADD", "Addis Ababa Bole International", "Addis Ababa", "Ethiopia"],
  ["NBO", "Jomo Kenyatta International", "Nairobi", "Kenya"],
  ["DAR", "Julius Nyerere International", "Dar es Salaam", "Tanzania"],
  ["ZNZ", "Abeid Amani Karume International", "Zanzibar", "Tanzania"],
  ["JNB", "O.R. Tambo International", "Johannesburg", "South Africa"],
  ["CPT", "Cape Town International", "Cape Town", "South Africa"],
  ["DUR", "King Shaka International", "Durban", "South Africa"],
  ["MRU", "Sir Seewoosagur Ramgoolam International", "Mauritius", "Mauritius"],
  ["SEZ", "Seychelles International", "Mahé", "Seychelles"],
  // Asia
  ["NRT", "Narita International", "Tokyo", "Japan"],
  ["HND", "Haneda", "Tokyo", "Japan"],
  ["KIX", "Kansai International", "Osaka", "Japan"],
  ["NGO", "Chubu Centrair International", "Nagoya", "Japan"],
  ["CTS", "New Chitose", "Sapporo", "Japan"],
  ["FUK", "Fukuoka", "Fukuoka", "Japan"],
  ["OKA", "Naha", "Okinawa", "Japan"],
  ["ICN", "Incheon International", "Seoul", "South Korea"],
  ["GMP", "Gimpo International", "Seoul", "South Korea"],
  ["PUS", "Gimhae International", "Busan", "South Korea"],
  ["PEK", "Beijing Capital International", "Beijing", "China"],
  ["PKX", "Beijing Daxing International", "Beijing", "China"],
  ["PVG", "Shanghai Pudong International", "Shanghai", "China"],
  ["SHA", "Shanghai Hongqiao International", "Shanghai", "China"],
  ["CAN", "Guangzhou Baiyun International", "Guangzhou", "China"],
  ["SZX", "Shenzhen Bao'an International", "Shenzhen", "China"],
  ["CTU", "Chengdu Shuangliu International", "Chengdu", "China"],
  ["XIY", "Xi'an Xianyang International", "Xi'an", "China"],
  ["HGH", "Hangzhou Xiaoshan International", "Hangzhou", "China"],
  ["HKG", "Hong Kong International", "Hong Kong", "Hong Kong"],
  ["MFM", "Macau International", "Macau", "Macau"],
  ["TPE", "Taiwan Taoyuan International", "Taipei", "Taiwan"],
  ["MNL", "Ninoy Aquino International", "Manila", "Philippines"],
  ["CEB", "Mactan-Cebu International", "Cebu", "Philippines"],
  ["SGN", "Tan Son Nhat International", "Ho Chi Minh City", "Vietnam"],
  ["HAN", "Noi Bai International", "Hanoi", "Vietnam"],
  ["DAD", "Da Nang International", "Da Nang", "Vietnam"],
  ["BKK", "Suvarnabhumi", "Bangkok", "Thailand"],
  ["DMK", "Don Mueang International", "Bangkok", "Thailand"],
  ["HKT", "Phuket International", "Phuket", "Thailand"],
  ["CNX", "Chiang Mai International", "Chiang Mai", "Thailand"],
  ["SIN", "Changi", "Singapore", "Singapore"],
  ["KUL", "Kuala Lumpur International", "Kuala Lumpur", "Malaysia"],
  ["PEN", "Penang International", "Penang", "Malaysia"],
  ["CGK", "Soekarno-Hatta International", "Jakarta", "Indonesia"],
  ["DPS", "Ngurah Rai International", "Bali / Denpasar", "Indonesia"],
  ["SUB", "Juanda International", "Surabaya", "Indonesia"],
  ["PNH", "Phnom Penh International", "Phnom Penh", "Cambodia"],
  ["REP", "Siem Reap-Angkor International", "Siem Reap", "Cambodia"],
  ["DEL", "Indira Gandhi International", "Delhi", "India"],
  ["BOM", "Chhatrapati Shivaji Maharaj International", "Mumbai", "India"],
  ["BLR", "Kempegowda International", "Bengaluru", "India"],
  ["MAA", "Chennai International", "Chennai", "India"],
  ["HYD", "Rajiv Gandhi International", "Hyderabad", "India"],
  ["CCU", "Netaji Subhas Chandra Bose International", "Kolkata", "India"],
  ["COK", "Cochin International", "Kochi", "India"],
  ["GOI", "Goa Dabolim", "Goa", "India"],
  ["CMB", "Bandaranaike International", "Colombo", "Sri Lanka"],
  ["MLE", "Velana International", "Male", "Maldives"],
  ["KTM", "Tribhuvan International", "Kathmandu", "Nepal"],
  ["DAC", "Hazrat Shahjalal International", "Dhaka", "Bangladesh"],
  ["ISB", "Islamabad International", "Islamabad", "Pakistan"],
  ["KHI", "Jinnah International", "Karachi", "Pakistan"],
  ["LHE", "Allama Iqbal International", "Lahore", "Pakistan"],
  ["TAS", "Tashkent International", "Tashkent", "Uzbekistan"],
  ["ALA", "Almaty International", "Almaty", "Kazakhstan"],
  ["TBS", "Tbilisi International", "Tbilisi", "Georgia"],
  ["EVN", "Zvartnots International", "Yerevan", "Armenia"],
  ["GYD", "Heydar Aliyev International", "Baku", "Azerbaijan"],
  // Oceania
  ["SYD", "Sydney Kingsford Smith", "Sydney", "Australia"],
  ["MEL", "Melbourne Tullamarine", "Melbourne", "Australia"],
  ["BNE", "Brisbane", "Brisbane", "Australia"],
  ["PER", "Perth", "Perth", "Australia"],
  ["ADL", "Adelaide", "Adelaide", "Australia"],
  ["OOL", "Gold Coast", "Gold Coast", "Australia"],
  ["CNS", "Cairns", "Cairns", "Australia"],
  ["AKL", "Auckland", "Auckland", "New Zealand"],
  ["WLG", "Wellington", "Wellington", "New Zealand"],
  ["CHC", "Christchurch", "Christchurch", "New Zealand"],
  ["ZQN", "Queenstown", "Queenstown", "New Zealand"],
  ["NAN", "Nadi International", "Nadi", "Fiji"],
  ["PPT", "Faa'a International", "Papeete / Tahiti", "French Polynesia"],
];

export function searchAirports(query: string, limit = 6): Airport[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const scored: { airport: Airport; score: number }[] = [];
  for (const airport of AIRPORTS) {
    const [code, name, city, country] = airport;
    const codeL = code.toLowerCase();
    const cityL = city.toLowerCase();
    const nameL = name.toLowerCase();

    let score = 0;
    if (codeL === q) score = 100;
    else if (codeL.startsWith(q)) score = 90;
    else if (cityL.startsWith(q)) score = 80;
    else if (nameL.startsWith(q)) score = 70;
    else if (cityL.includes(q)) score = 60;
    else if (nameL.includes(q)) score = 50;
    else if (country.toLowerCase().startsWith(q)) score = 30;
    if (score > 0) scored.push({ airport, score });
  }

  return scored
    .sort((a, b) => b.score - a.score || a.airport[2].localeCompare(b.airport[2]))
    .slice(0, limit)
    .map((s) => s.airport);
}

/** "IST" stays IST; "Istanbul" resolves to IST; unknown text returns null. */
export function resolveAirportCode(text: string): string | null {
  const trimmed = text.trim();
  if (/^[A-Za-z]{3}$/.test(trimmed)) return trimmed.toUpperCase();
  const [top] = searchAirports(trimmed, 1);
  return top ? top[0] : null;
}

export function cityForCode(code: string): string | null {
  const upper = code.toUpperCase();
  const found = AIRPORTS.find((a) => a[0] === upper);
  return found ? found[2] : null;
}
